# Golden extraction tests for the shipped PDF templates, plus the guard that keeps
# them honest.
#
# WHY THIS FILE EXISTS. "Proven" (the set that gates the Qlik feed, R/feed.R) meant
# only "the YAML sits in templates/" -- nothing verified it parsed anything. Three of
# the five PDF templates had no parse test at all: an analyst could nudge a column
# band, run the whole suite green, and ship silently-wrong conversions to the
# dashboards. PDFs are the dominant input and x-band drift is invisible to the eye,
# so each shipped PDF template now parses a committed fixture and is compared to a
# golden snapshot, byte for byte.
#
# The fixtures are SYNTHETIC statements generated by fixtures/make_pdf_fixtures.R
# (a fictional bank, invented figures) so no real customer data is committed. They
# reproduce each bank's real column geometry, which is what the template encodes.

PDF_GOLDENS <- list(
  list(id = "anz_everyday_pdf",
       fx = "tests/testthat/fixtures/anz_everyday_pdf_sample.pdf",
       exp = "tests/testthat/expected/anz_everyday_pdf.csv"),
  list(id = "asb_everyday_pdf",
       fx = "tests/testthat/fixtures/asb_everyday_pdf_sample.pdf",
       exp = "tests/testthat/expected/asb_everyday_pdf.csv"),
  list(id = "westpac_everyday_pdf",
       fx = "tests/testthat/fixtures/westpac_everyday_pdf_sample.pdf",
       exp = "tests/testthat/expected/westpac_everyday_pdf.csv")
)

for (.g in PDF_GOLDENS) local({
  g <- .g
  test_that(sprintf("%s extracts its fixture to the golden table", g$id), {
    skip_if_not(requireNamespace("pdftools", quietly = TRUE))
    skip_if_not(file.exists(fixture(g$fx)))
    skip_if_not(file.exists(fixture(g$exp)))
    expect_statement_ok(g$fx, g$exp, template_id = g$id)
  })
})

# The guard: a template cannot join the proven set (and therefore the Qlik feed)
# without a fixture + golden pair. If this fails, either add the pair or state the
# exemption here with the reason -- do not delete the test.
test_that("every proven template has a fixture and a golden snapshot", {
  tdir <- templates_dir()
  skip_if_not(dir.exists(tdir))
  ids <- sub("\\.ya?ml$", "", basename(list.files(tdir, pattern = "\\.ya?ml$")))
  # tutorial_everyday_pdf is the bundled teaching specimen: R/templates.R excludes
  # it from production detection, but it DOES carry a golden, so it is not exempt.
  have_golden <- vapply(ids, function(id)
    file.exists(fixture(file.path("tests", "testthat", "expected", paste0(id, ".csv")))),
    logical(1))
  expect_identical(ids[!have_golden], character(0))
})
