# Golden extraction tests for the bank PDF samples, plus the guard that keeps
# them honest.
#
# WHY THIS FILE EXISTS. PDFs are the dominant input and a misplaced column is
# invisible to the eye, so each bank PDF sample is read to a golden snapshot, byte
# for byte: by the automatic reader, which must PROVE it with no template (the
# path every statement now takes), and by the table reader with the fixture
# template (the reader the automatic one assembles its rows with).
#
# The fixtures are SYNTHETIC statements generated by fixtures/make_pdf_fixtures.R
# (a fictional bank, invented figures) so no real customer data is committed. They
# reproduce each bank's real column geometry.

PDF_GOLDENS <- list(
  list(id = "anz_everyday_pdf",
       fx = "tests/testthat/fixtures/anz_everyday_pdf_sample.pdf",
       exp = "tests/testthat/expected/anz_everyday_pdf.csv"),
  list(id = "asb_everyday_pdf",
       fx = "tests/testthat/fixtures/asb_everyday_pdf_sample.pdf",
       exp = "tests/testthat/expected/asb_everyday_pdf.csv"),
  list(id = "westpac_everyday_pdf",
       fx = "tests/testthat/fixtures/westpac_everyday_pdf_sample.pdf",
       exp = "tests/testthat/expected/westpac_everyday_pdf.csv")
)

for (.g in PDF_GOLDENS) local({
  g <- .g
  test_that(sprintf("%s: the automatic reader proves its fixture to the golden table", g$id), {
    skip_if_not(requireNamespace("pdftools", quietly = TRUE))
    skip_if_not(file.exists(fixture(g$fx)))
    expect_auto_read_golden(g$fx, g$exp, outcomes = "proven")
  })
  test_that(sprintf("%s: the fixture template extracts its fixture to the golden table", g$id), {
    skip_if_not(requireNamespace("pdftools", quietly = TRUE))
    skip_if_not(file.exists(fixture(g$fx)))
    expect_statement_ok(g$fx, g$exp, template_id = g$id)
  })
})

# The guard: every fixture template carries a golden snapshot, so no reader test
# can lean on a template whose output nobody has pinned. If this fails, add the
# pair or state the exemption here with the reason -- do not delete the test.
test_that("every fixture template has a golden snapshot", {
  ids <- names(fixture_templates())
  expect_gt(length(ids), 0L)
  have_golden <- vapply(ids, function(id)
    file.exists(fixture(file.path("tests", "testthat", "expected", paste0(id, ".csv")))),
    logical(1))
  expect_identical(ids[!have_golden], character(0))
})
